mysql:
    docker:
        username: root
        password: martha
        port: 3316
        database: vin
    vin:
        username: root
        password: martha
        database: vin
interval: 10s